social:
  label: 社交资料
  items:
    Github:
      name: Github 
      label: Github 
      type: text          
      placeholder: '填入 Github 链接'
    email_address:
      name: email_address
      label: 邮箱
      type: email
      placeholder: '填入 邮箱地址'
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: '填入 微博Id' 
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: '填入 QQ号'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '填入 Telegram Id'
    twitter_account:
      name: twitter_account
      label: Twitter
      type: text
      placeholder: '填入 Twitter 用户名'
    facebook:
      name: facebook
      label: Facebook
      type: text
      placeholder: '填入 Facebook 用户名'
    instagram:
      name: instagram
      label: Instagram
      type: text
      placeholder: '填入 Instagram 用户名'

    RSS:
      name: RSS
      label: 首页显示RSS图标
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
home:
  label: 通用设置
  items:
    hitokoto:
      name: hitokoto
      label: 首页展示一言（开启后描述语将失效）
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭