social:
  label: 社交资料
  items:
    Github:
      name: Github 
      label: Github 
      type: text          
      placeholder: '填入 Github 链接'
    email_address:
      name: email_address
      label: 邮箱
      type: email
      placeholder: '填入 邮箱地址'
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: '填入 微博Id' 
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: '填入 QQ号'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '填入 Telegram Id'
    twitter_account:
      name: twitter_account
      label: Twitter
      type: text
      placeholder: '填入 Twitter 用户名'
    facebook:
      name: facebook
      label: Facebook
      type: text
      placeholder: '填入 Facebook 用户名'
    instagram:
      name: instagram
      label: Instagram
      type: text
      placeholder: '填入 Instagram 用户名'

    RSS:
      name: RSS
      label: 首页显示RSS图标
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
home:
  label: 通用设置
  items:
    hitokoto:
      name: hitokoto
      label: 是否开启一言
      type: radio
      description: "注意：开启后，所有页面描述将变为一言"
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_comment:
      name: post_comment
      label: 开启文章评论
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
page_title:
  label: 自定义页面标题
  items:
    journals_title:
      name: journals_title
      label: 日志页面标题
      type: text
      default: 日志
    photos_title:
      name: photos_title
      label: 相册页面标题
      type: text
      default: 相册
    links_title:
      name: links_title
      label: 友情链接页面名称
      type: text
      default: 友情链接
    tags_title:
      name: tags_title
      label: 标签页面名称
      type: text
      default: 标签
    archives_title:
      name: archives_title
      label: 归档页面名称
      type: text
      default: 归档
    categories_title:
      name: categories_title
      label: 分类页面名称
      type: text
      default: 分类栏目
page_description:
  label: 自定义页面描述
  items:
    journals_description:
      name: journals_description
      label: 日志页面描述
      type: text
      description: "注意：所有如果开启了一言，将覆盖描述"
    photos_description:
      name: photos_description
      label: 相册页面描述
      type: text
    links_description:
      name: links_description
      label: 友情链接页面描述
      type: text
    tags_description:
      name: tags_description
      label: 标签页面描述
      type: text
    archives_description:
      name: archives_description
      label: 归档页面描述
      type: text
    categories_description:
      name: categories_description
      label: 分类页面描述
      type: text
other:
  label: 其他
  items:
    TimeStatistics:
      name: TimeStatistics
      label: "站点运行时间统计"
      type: text
      description: "填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00"
